// Editorial narratives supplement the source-checked results in generate-journal.mjs.
// Figure positions refer to the result they explain, preserving the paper's figure numbers.
export const journalFigureDimensions = {
  'cfe-exfoliation-yield.jpg': [1320, 610],
  'cold-to-hot-cop.jpg': [760, 530],
  'xn4-anisotropy.jpg': [770, 370],
  'tio2-interface.jpg': [725, 600],
  'graphene-helium-argon.jpg': [1050, 560],
  'mlip-review-comparison.jpg': [1160, 480],
  'c2n-thermal-conductivity.jpg': [760, 690],
  'c2n-tensile-strength.jpg': [1650, 1080],
  'silicon-size-thermal.jpg': [800, 630],
  'silicon-width-mechanics.jpg': [1490, 1170],
  'borophene-pore-design.jpg': [1400, 565],
  'torsional-wrinkles.jpg': [600, 590],
  'nanoparticle-water-shells.jpg': [1200, 600],
  'nanofluid-nanolayer-density.jpg': [715, 605],
};

export const journalStories = [
  {
    headline: 'Following the energy behind graphene separation.',
    standfirst: 'A fast gas stream can pull graphene layers apart. This study asks what happens along the way, mapping the energy landscape of different separation routes.',
    highlight: { value: 'Free energy', label: 'A common measure for comparing exfoliation pathways' },
    openingTitle: 'A separation has more than one route',
    bridge: 'For a production process, the route matters as much as the final separated sheet. A layer can move through configurations with different energetic costs. Understanding those costs gives process design a more useful starting point than observing the final motion alone.',
    methodsTitle: 'Tracing the path, configuration by configuration',
    methodNote: 'A potential-of-mean-force calculation describes how free energy changes along a chosen separation coordinate. Combining it with molecular dynamics connects the motion of the gas and sheets to the energetic landscape that the layers encounter.',
    scenes: [
      { title: 'From layer motion to an energy landscape', explanation: 'This shifts the focus from whether separation occurs to how it proceeds. Profiles allow pathways to be compared on the same energetic basis, including the configurations encountered before the layers are fully apart.' },
      { title: 'The gas and the sheet belong in the same picture', explanation: 'The imposed flow sets the environment, while the number of layers, sheet dimensions, and defects describe the material being processed. Exploring both sides of that interaction is necessary for a map that can inform process choices.' },
      { title: 'Turning the map into a process question', explanation: 'The practical question becomes which combination of material and gas conditions offers a favorable route to separation. The linked publication contains the profiles and detailed parameter comparisons needed to evaluate particular operating choices.' },
    ],
    endingTitle: 'An energetic foundation for scaling up',
    endingNote: 'The story here introduces the framework and the variables it connects. For a specific pathway or operating condition, the original publication is the place to examine the quantitative maps.',
    figureResults: [],
  },
  {
    headline: 'What actually starts a layer separating?',
    standfirst: 'High-pressure gas can turn layered powders into thin sheets. Experiments and gas-flow analysis reveal where the force that starts exfoliation comes from.',
    highlight: { value: '≈30 μN', label: 'Exfoliation initiation cutoff in the tested setup' },
    openingTitle: 'The force hidden inside the flow',
    bridge: 'A converging–diverging nozzle accelerates the gas and can also produce shocks. Both are striking features of compressible flow, but their presence does not establish which one starts the layers moving apart. The mechanism has to be tested against the material leaving the apparatus.',
    methodsTitle: 'Putting the nozzle and the shock to the test',
    methodNote: 'The shock-tube comparison helps distinguish a shock event from the accelerating flow in a nozzle. Optical absorbance provides an experimental signal for comparing the resulting h-BN dispersions across the tested conditions.',
    scenes: [
      { title: 'Acceleration supplies the initiating thrust', explanation: 'The location of that thrust changes the design question. The nozzle throat, where the gas accelerates, becomes central to understanding how force is applied to the layered particles before their subsequent motion through the flow.' },
      { title: 'A force threshold connects calculation and experiment', explanation: 'The cutoff links the calculated force on the sheets with the measured absorbance ratios. It is a result for this apparatus and these conditions, giving a concrete benchmark for the proposed mechanism.' },
      { title: 'Helium changes the experimental outcome', explanation: 'In the selected figure, the spectra and the comparison at 300 nm tell the same story: changing the carrier gas can improve the exfoliation signal even when the supply pressure is lower. Pressure alone therefore does not describe the process.' },
    ],
    endingTitle: 'Design around the force the layers receive',
    endingNote: 'Together, the experiment and flow calculation make the initiation mechanism more specific. They also give future nozzle studies something measurable to connect: gas acceleration, thrust on the sheets, and the resulting dispersion.',
    figureResults: [2],
    figureReadings: ['Compare the helium and nitrogen absorbance, especially the 1.4 MPa helium and 5.6 MPa nitrogen cases.'],
  },
  {
    headline: 'Making heat travel from cold to hot.',
    standfirst: 'Two nanoparticles become a model refrigerator when their interactions are deliberately unequal. The work follows the reversed heat flow, its energy cost, and its fluctuations.',
    highlight: { value: 'Cold → hot', label: 'Heat pumping powered by nonreciprocal forces' },
    openingTitle: 'Changing the direction of a familiar process',
    bridge: 'At nanoparticle scales, thermal motion is noisy and the heat transferred in a short interval fluctuates. A useful refrigerator has to sustain the desired average flow while accounting for the work that drives it and the variability of its output.',
    methodsTitle: 'An atomistic experiment with a simpler theory',
    methodNote: 'The molecular simulation resolves the particles and their surrounding gas. The reduced model makes it possible to write analytical expressions for heat, work, and efficiency, then compare those predictions with the atomistic trajectories.',
    scenes: [
      { title: 'Unequal interactions open a cooling regime', explanation: 'The coupling strengths on the hot and cold sides provide the control parameters. By changing their ratio, the system moves between different heat-flow regimes, including one in which energy is extracted from the colder reservoir.' },
      { title: 'Efficiency rises toward a thermodynamic limit', explanation: 'The coefficient of performance compares heat removed from the cold side with the work supplied. The peak near the matching condition is the useful feature of the selected plot; it also identifies how the coupling ratio controls efficiency.' },
      { title: 'Cooling power comes with fluctuations', explanation: 'The strongest average cooling and the smallest uncertainty are close in parameter space, but they answer different questions. The theory connects those fluctuations to entropy production, making precision part of the refrigerator design problem.' },
    ],
    endingTitle: 'Control the current and understand its cost',
    endingNote: 'This is a molecular simulation and theoretical model of refrigeration. Its contribution is a set of conditions and thermodynamic relationships that explain how controlled interactions can redirect heat at small scales.',
    figureResults: [1],
    figureReadings: ['Follow the efficiency as the coupling ratio approaches the temperature-matching condition.'],
  },
  {
    headline: 'Three sheets, two directions, different answers.',
    standfirst: 'BeN₄, MgN₄, and PtN₄ reveal how chemistry and lattice direction shape heat flow and stiffness, and how those differences change with temperature.',
    highlight: { value: '≈0.4', label: 'Nearly temperature-independent mechanical anisotropy in BeN₄ and MgN₄' },
    openingTitle: 'A material property depends on which way you look',
    bridge: 'A directional crystal cannot be fully described by one stiffness or conductivity value. Comparing the same property along armchair and zigzag directions reveals the influence of lattice structure; repeating the comparison at different temperatures shows whether that contrast is stable.',
    methodsTitle: 'Learning the interactions, then testing the sheets',
    methodNote: 'The learned potential makes the first-principles training data usable in longer molecular-dynamics simulations. The thermal and tensile calculations are performed separately, so their directional responses can be compared without assuming they follow the same ranking.',
    scenes: [
      { title: 'Armchair and zigzag do not respond equally', explanation: 'The preferred direction is broadly shared, but the magnitude is material-specific. Replacing Be with Mg or Pt changes the interaction landscape and the contrast between the two directions.' },
      { title: 'Heating reveals two kinds of anisotropy', explanation: 'The selected plot compares a normalized directional difference in elastic modulus. A lower value means the two directions are more similar. The nearly flat BeN₄ and MgN₄ curves contrast with PtN₄, whose directional difference diminishes as the sheet heats up.' },
      { title: 'The thermal ranking is clearer than the mechanical one', explanation: 'For conductivity, BeN₄ leads and PtN₄ trails in both directions. The stiffness ranking also depends on direction, so a material chosen for heat transport need not offer the highest mechanical stiffness in every orientation.' },
    ],
    endingTitle: 'Choose the chemistry and the orientation together',
    endingNote: 'The study gives a directional view of these monolayers. Those distinctions are useful whenever a sheet must carry heat or a tensile load along a particular axis, especially over a changing temperature range.',
    figureResults: [1],
    figureReadings: ['Look for the flat BeN₄ and MgN₄ curves and the falling PtN₄ curve; the vertical axis measures mechanical anisotropy.'],
  },
  {
    headline: 'Where a hot nanoparticle meets water.',
    standfirst: 'For TiO₂ in water, cooling depends on the molecular contact at the surface. Simulations show how temperature, particle size, and interaction strength change that exchange.',
    highlight: { value: '≈20%', label: 'Conductance increase when the interaction parameter rises from 0.5 to 4' },
    openingTitle: 'The boundary is part of the heat-transfer problem',
    bridge: 'Even a particle that conducts heat well internally must pass its energy across a solid–liquid boundary. Measuring that boundary separately helps explain why two particles in the same liquid can cool differently, and why the surface interaction belongs in the model.',
    methodsTitle: 'Watching a heated particle relax',
    methodNote: 'The transient follows the particle as it releases energy to water. Changing one parameter at a time separates the effects of particle diameter, initial temperature, and wettability. A continuum calculation then checks how those interface properties translate into a cooling curve.',
    scenes: [
      { title: 'TiO₂ makes an efficient thermal contact', explanation: 'The comparison is with the other systems discussed in the paper. It establishes the scale of the TiO₂–water interface response before the study asks which parameters can move that response further.' },
      { title: 'A larger particle slightly lowers conductance', explanation: 'Conductance measures transfer per unit interface area and temperature difference. The modest diameter dependence therefore describes the boundary response, rather than simply the total amount of heat stored in a larger particle.' },
      { title: 'Stronger molecular contact raises the exchange', explanation: 'The plot brings temperature and interaction strength into one view: hotter particles and stronger solid–liquid interactions both raise conductance. The paper also tests electrostatic interactions; omitting the Coulombic contribution reduces the modeled conductance by about two orders of magnitude, showing how strongly the assumed interaction model matters.' },
    ],
    endingTitle: 'Model the contact as carefully as the particle',
    endingNote: 'The simulations connect an interface-scale property to the particle’s cooling transient. They show why surface coupling and the representation of electrical interactions deserve attention when predicting heat release into water.',
    figureResults: [2],
    figureReadings: ['Follow each curve with increasing temperature, then compare curves for different interaction strengths.'],
  },
  {
    headline: 'How a gas stream moves graphene apart.',
    standfirst: 'At the scale of individual atoms, helium and argon produce very different motions. A molecular view connects gas choice, supersonic flow, and the pathway of graphene exfoliation.',
    highlight: { value: '>16 Å', label: 'Graphene-layer root-mean-square displacement in the helium comparison' },
    openingTitle: 'From a moving gas to a moving sheet',
    bridge: 'Graphene layers are held together by interlayer attraction. To separate them, a flowing gas must do more than surround the sheets: it must transfer momentum and energy in a way that produces relative layer motion. The direction of that motion is part of the mechanism.',
    methodsTitle: 'Resolving the collisions that drive exfoliation',
    methodNote: 'The simulations impose directional gas flow to represent the moving gas in the process. Tracking motion and interlayer energy together helps distinguish a vibrating bilayer from one progressing toward separation.',
    scenes: [
      { title: 'Sliding provides a favorable separation route', explanation: 'The atomistic picture points toward motion parallel to the sheets. That route is consistent with the preference for sliding found in the simulations and gives a physical interpretation of how a fast stream can begin to loosen a bilayer.' },
      { title: 'The lighter gas produces a larger response', explanation: 'The left panel measures root-mean-square displacement rather than a single final separation distance. The helium trace rises sharply, while argon remains much lower. The right panel adds the distribution of interlayer interaction energy, providing a second view of the different bilayer responses.' },
      { title: 'Supply pressure changes the energy delivered', explanation: 'In the process, upstream pressure is connected to gas density and flow velocity. The pressure comparison therefore links an operating setting to the energy absorbed by the graphene, extending the mechanism beyond gas identity alone.' },
    ],
    endingTitle: 'Gas choice becomes a material-processing variable',
    endingNote: 'The results describe the modeled gas and bilayer conditions. Their value for process development is the connection between operating conditions, atomic motion, and a plausible layer-separation pathway.',
    figureResults: [1],
    figureReadings: ['Compare the displacement traces on the left; use the energy distributions on the right as a complementary measure of the layer interaction.'],
  },
  {
    headline: 'Learning atomic forces to predict heat flow.',
    standfirst: 'A perspective on machine learning potentials: how first-principles data can support larger thermal-transport simulations, and what makes their predictions trustworthy.',
    highlight: { value: 'From atoms', label: 'Learned interactions connect reference calculations to larger simulations' },
    openingTitle: 'Accuracy and simulation size pull in different directions',
    bridge: 'Thermal transport depends on lattice vibrations across many atoms and over time. That makes a fast, accurate representation of atomic forces especially valuable. Machine learning offers a way to build that representation from reference calculations, but its usefulness has to be demonstrated for the target material.',
    methodsTitle: 'Following the evidence across published studies',
    methodNote: 'This is a perspective, so the comparisons bring together results from the literature. They help readers understand the methods and their performance across materials, rather than reporting a single new experiment or a universal benchmark.',
    scenes: [
      { title: 'A learned potential extends what can be simulated', explanation: 'Once trained, the potential supplies forces during molecular dynamics without repeating the full electronic-structure calculation at every step. This enables the cell sizes and trajectories needed to study thermal transport more practically.' },
      { title: 'Conductivity comparisons show both promise and variation', explanation: 'Read each group in the figure as a comparison within one material. The agreement between approaches supports the promise of learned potentials, while their differences show why reference data and method choices still need to be examined case by case.' },
      { title: 'The training set sets the reach of the model', explanation: 'A potential learns from the configurations it sees. Validation of vibrational behavior and transport predictions is therefore part of using the method, especially when simulations move to temperatures or deformations beyond those represented in training.' },
    ],
    endingTitle: 'A useful bridge, with validation built in',
    endingNote: 'The perspective places individual successes in a broader methodological picture. It is a starting point for choosing and evaluating a learned potential for a thermal-transport problem.',
    figureResults: [1],
    figureReadings: ['Compare methods within each material; the spread shows that agreement depends on the system being modeled.'],
  },
  {
    headline: 'The model changes the story of C₂N.',
    standfirst: 'A porous carbon–nitrogen sheet carries heat, stretches, and eventually breaks. Comparing two atomic models reveals different predictions at every stage.',
    highlight: { value: '85.5 ± 3', unit: 'W/m·K', label: 'Room-temperature conductivity predicted by the learned potential' },
    openingTitle: 'A sheet with holes, and a question about its atoms',
    bridge: 'To simulate the sheet, every atomic force has to come from a model. That choice affects the vibrations that carry heat and the bonds that resist stretching. This study follows both properties in the same material, testing whether a learned model can represent them consistently.',
    methodsTitle: 'Build the model before trusting the prediction',
    methodNote: 'The training configurations span 50–1000 K. The learned moment tensor potential reproduces the acoustic phonon branches well against the DFT reference, with some deviations in the optical branches. That check comes before the larger heat-flow and tensile simulations, giving the transport results a physical foundation.',
    scenes: [
      { title: 'First, let heat travel through a longer sheet', explanation: 'The rising curves are a size effect: short samples restrict the distance heat-carrying phonons can travel. Extrapolating toward a long sheet separates that finite-size effect from the material’s intrinsic conductivity. The MLIP trend approaches the cited DFT-BTE reference more closely than the Tersoff trend; the difference persists beyond the individual simulated lengths.' },
      { title: 'Then stretch the same material toward failure', explanation: 'The initial slope measures stiffness, but the rest of the curve tells a different part of the story. The learned model predicts a more gradual rupture than Tersoff. In the snapshots, increasing strain redistributes local stress before atomic bonds break, connecting the macroscopic curve to the material’s atomic failure process.' },
      { title: 'A few missing atoms change how the sheet fails', explanation: 'The defective-sheet simulations locate failure around the vacancies, where stress concentrates and bonds rupture. The much smaller change in elastic modulus means early stretching can look relatively similar even when the response near failure has changed substantially.' },
    ],
    endingTitle: 'A reliable model has to follow more than one property',
    endingNote: 'For this sheet, the learned potential moves the heat-flow and stiffness predictions closer to the cited first-principles references and permits a study of vacancy-driven failure. The evidence also makes clear why conductivity alone is an incomplete test of a material model.',
    figureResults: [0, 1],
    figureReadings: [
      'Read from left to right as sheet length increases. Compare the MLIP and Tersoff trends with the horizontal DFT-BTE reference.',
      'Start with the slope of the stress–strain curves, then follow the snapshots to see how loading develops into bond rupture.',
    ],
  },
  {
    headline: 'Silicon changes when the wire gets small.',
    standfirst: 'A nanowire is more than a miniature piece of bulk silicon. Its dimensions and surfaces reshape heat transport, stiffness, and the way it breaks.',
    highlight: { value: '10–45 nm', label: 'Wire lengths examined in the molecular simulations' },
    openingTitle: 'At small sizes, the surface becomes unavoidable',
    bridge: 'Shrinking a wire increases the share of atoms influenced by a surface. Length also limits the distance available for heat transport. Looking at length and width separately makes it possible to see which geometric feature is changing the response.',
    methodsTitle: 'Change the dimensions, then heat and stretch',
    methodNote: 'The study compares geometry-dependent transport with tensile behavior and examines temperature effects separately. It also considers a quantum correction to the classical conductivity calculation, which changes the apparent temperature dependence.',
    scenes: [
      { title: 'Longer wires carry heat more effectively', explanation: 'The selected length plot holds the cross-section fixed, isolating one size effect. The paper also extrapolates the conductivity: widths of 4.3 and 6.5 nm give long-wire estimates of 3.8 and 6.2 W/m·K, respectively. Length and width both matter when assigning a value to a nanowire.' },
      { title: 'A wider cross-section improves the mechanical response', explanation: 'The stress–strain curves provide the direct response to stretching, while the remaining panels summarize stiffness and failure as width changes. Together they show how the mechanical penalty of a small cross-section appears in several properties, rather than in a single strength value.' },
      { title: 'Temperature adds a separate mechanical penalty', explanation: 'Across the temperature comparison, the reported Young’s modulus decreases from 80.1 to 69.2 GPa. For heat flow, the quantum-corrected calculations are less sensitive to temperature than the uncorrected classical results, so the temperature trend must be read with the calculation method in mind.' },
    ],
    endingTitle: 'Specify the wire before specifying its properties',
    endingNote: 'The findings provide a geometry- and temperature-dependent view of [110] silicon nanowires. They make dimensions part of the material description needed for a thermal or mechanical design.',
    figureResults: [0, 1],
    figureReadings: ['Follow the conductivity as length increases at a fixed cross-section.', 'Compare the curves and summary panels as the cross-section width grows.'],
  },
  {
    headline: 'Shaping holes to reshape borophene.',
    standfirst: 'Borophene naturally behaves differently along two directions. Engineered pores offer a way to tune that contrast through geometry.',
    highlight: { value: 'Pore shape', label: 'A design variable for directional heat flow and stiffness' },
    openingTitle: 'Turning directional behavior into a design choice',
    bridge: 'Adding holes changes how a sheet carries load and heat, but the total missing area is only part of the story. An elongated pore interrupts the two lattice directions differently. Its shape and orientation can therefore tune the directional contrast.',
    methodsTitle: 'Compare pore architectures at the same scale',
    methodNote: 'The study compares pore shape, orientation, and porosity through both atomistic and continuum calculations. Their agreement in the main trends tests whether the design principle survives a change in modeling scale.',
    scenes: [
      { title: 'The aspect ratio moves the directional balance', explanation: 'Changing the long-to-short axis ratio of an elliptical pore changes the paths available for heat and load. This makes the pore architecture a controllable feature of the material response.' },
      { title: 'Some pore shapes bring the directions together', explanation: 'The plotted anisotropy approaches zero when the armchair and zigzag conductivity values become similar. The different panels show why there is no single pore aspect ratio for every porosity: the geometry that minimizes the contrast shifts with the amount of missing material.' },
      { title: 'Tuning anisotropy also changes absolute performance', explanation: 'The paper reports more than a 50% reduction in conductivity in both directions at 30% porosity. A design that improves directional balance therefore still has to be evaluated for its total conductivity and mechanical response. FEM captures the principal trends, while the atomistic model includes size effects.' },
    ],
    endingTitle: 'The pore is part of the material architecture',
    endingNote: 'The study makes anisotropy a property that can be engineered. Choosing a pore design means balancing directional uniformity with the reduction in heat transport and mechanical performance caused by removing material.',
    figureResults: [1],
    figureReadings: ['Look for the minima near zero in each porosity panel, then compare the MD and FEM locations of those minima.'],
  },
  {
    headline: 'A twist leaves its mark on heat flow.',
    standfirst: 'Twisting an atomically thin sheet creates wrinkles. Graphene, h-BN, and MoS₂ respond differently as those wrinkles interrupt thermal transport.',
    highlight: { value: 'MoS₂', label: 'The strongest conductivity reduction of the three sheets compared' },
    openingTitle: 'Deformation changes the path for lattice vibrations',
    bridge: 'A sheet used under mechanical loading may no longer have the geometry of a pristine flat crystal. By connecting wrinkle amplitude with conductivity, the study asks whether the visible deformation can explain the change in heat transport.',
    methodsTitle: 'Twist a ring and follow the heat',
    methodNote: 'The modeled sheets have a ring geometry, with torsion applied at the inner boundary. Varying the geometry and deformation allows the authors to relate the developing wrinkles to both conductivity and the vibrational response.',
    scenes: [
      { title: 'Larger wrinkles reduce the carried heat', explanation: 'The conductivity is normalized by each material’s pristine value. This removes the difference in their starting conductivities and exposes how much of the original transport survives the deformation.' },
      { title: 'The same deformation does not have the same cost', explanation: 'In the selected comparison, MoS₂ retains the smallest fraction of its starting conductivity and h-BN the largest. Graphene lies between them. The spread shows that wrinkle amplitude is useful, but the material’s own vibrational response also matters.' },
      { title: 'Ring geometry changes the wrinkle pattern', explanation: 'A larger inner radius produces additional wrinkles in the structures studied. The accompanying conductivity reduction and shift in vibrational spectra connect the imposed geometry to a microscopic explanation for the heat-flow change.' },
    ],
    endingTitle: 'Include the deformed shape in the thermal picture',
    endingNote: 'The findings are useful for interpreting heat transport in mechanically loaded 2D sheets. A conductivity assigned to a flat sheet can change once torsion and wrinkles become part of the structure.',
    figureResults: [1],
    figureReadings: ['The vertical axis is the fraction of pristine conductivity; compare how steeply each material falls as the normalized wrinkle amplitude increases.'],
  },
  {
    headline: 'The first water layers tell the cooling story.',
    standfirst: 'A hot silver nanoparticle releases its heat into a very small region of water. Following individual shells connects molecular motion to a continuum cooling model.',
    highlight: { value: '≈2 nm', label: 'The range of the strongest temperature disturbance around the particle' },
    openingTitle: 'Cooling starts in the water closest to the surface',
    bridge: 'An average liquid temperature can hide the first moments of a cooling event. Dividing the surrounding water into shells reveals where the heat goes first, how the response spreads, and which part of the liquid needs special treatment in a larger-scale model.',
    methodsTitle: 'Measure the interface, then resolve the surrounding liquid',
    methodNote: 'The four conductance approaches provide an additional check: steady-state non-equilibrium and equilibrium estimates agree, while the transient approaches give different results. That comparison highlights the importance of the measurement protocol when interpreting an interface value.',
    scenes: [
      { title: 'The disturbance is fast and spatially localized', explanation: 'The first shell has the largest temperature rise. Successive shells respond more weakly and later, so the plots describe both a cooling timescale and the limited spatial reach of the transient.' },
      { title: 'Water at the surface needs its own description', explanation: 'The enhanced conductivity is an effective value inferred through comparison with the continuum model. It represents the structured first shell, whose behavior differs from the water farther from the nanoparticle.' },
      { title: 'A continuum model can retain the molecular insight', explanation: 'Resolving the first shell improves the connection between the molecular trajectories and a heat-conduction calculation. The result offers a way to carry information about the interface into a model that does not track every water molecule.' },
    ],
    endingTitle: 'Keep the interface when changing modeling scale',
    endingNote: 'The study follows one localized cooling event through two descriptions. Its central lesson is to preserve the distinct near-surface region when translating molecular heat transfer into continuum behavior.',
    figureResults: [0],
    figureReadings: ['Compare the height and timing of the temperature peaks as the water shells move farther from the nanoparticle.'],
  },
  {
    headline: 'The water layer that changes a nanofluid.',
    standfirst: 'Silver nanoparticles organize the water around them. Accounting for that nanolayer changes how a mixture’s density and viscosity are predicted.',
    highlight: { value: '3 components', label: 'Particle, interfacial nanolayer, and remaining water' },
    openingTitle: 'The liquid near a particle is a distinct region',
    bridge: 'A conventional mixture relation counts a particle fraction and a water fraction. At nanoscales, the ordered water at the particle surface takes up a meaningful part of the system. Giving that region its own place in the model changes the volume balance.',
    methodsTitle: 'Build the mixture from its molecular structure',
    methodNote: 'The simulations provide the density and viscosity trends to test against mixture models. Particle size and nanolayer thickness determine how much of the liquid belongs to the interfacial region, making geometry part of the property calculation.',
    scenes: [
      { title: 'The nanolayer changes the available liquid volume', explanation: 'The contraction means the original particle and liquid volume fractions cannot simply be carried over unchanged. The three-component description accounts for the particle, the ordered shell, and the water remaining outside it.' },
      { title: 'The revised density relation follows the simulations', explanation: 'The selected plot compares that revised relation with molecular-dynamics values over particle diameter. Bringing the nanolayer into the calculation improves the density prediction, linking a microscopic structural feature to a measurable mixture property.' },
      { title: 'The shell also matters for viscosity', explanation: 'The viscosity comparison extends the argument beyond density. As particle concentration increases, the interfacial contribution becomes relevant to the predicted resistance to flow, so a purely binary description loses part of the molecular picture.' },
    ],
    endingTitle: 'Count the interfacial liquid as part of the mixture',
    endingNote: 'The work provides a molecular basis for revising simple mixture relations. Its practical contribution is a model in which the organized liquid at the particle surface has an explicit role in the fluid’s properties.',
    figureResults: [1],
    figureReadings: ['Compare the proposed three-component predictions with the MD points and the traditional binary relation as diameter changes.'],
  },
];
